sonata_admin:
    dashboard:
        groups:
            blog:
                label: Blog
                items:
                    - admin.blog_post
                    - admin.category

ivory_ck_editor:
    configs:
        my_config:
            toolbar: [ ["Source", "-", "Maximize"] ]
            uiColor: "#000000"