<?php

namespace YS\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends EntityRepository
{
  public function findAllOrderedByTitle()
  {
    return $this->getEntityManager()
      ->getRepository('YSBlogBundle:BlogPost')
      ->findBy(array('draft' => false, 'enabled' => true), array('createdAt' => 'ASC'))
    ;
  }
}