<?php

namespace YS\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use YS\BlogBundle\Entity\BlogPost;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends EntityRepository
{
  public function findAllOrderedByTitle()
  {
    return $this->getEntityManager()
      ->getRepository('YSBlogBundle:BlogPost')
      ->findBy(array('draft' => false, 'enabled' => true), array('createdAt' => 'ASC'))
    ;
  }

  public function findAllUsernameOrderedByUsername()
  {
    return $this->getEntityManager()
      ->createQueryBuilder()
      ->select('u.username')
      ->from('YSBlogBundle:BlogPost', 'b')
      ->leftJoin('b.user', 'u')
      ->where('b.draft = FALSE and b.enabled = TRUE')
      ->orderBy('u.username', 'ASC')
      ->distinct()
      ->getQuery()
      ->getResult();
  }
}